const { test, expect } = require('@playwright/test')

const password = 'synthetic-browser-password'
async function signIn(page, username, signup = true) {
  await page.goto('/')
  await page.locator('#user').fill(username)
  await page.locator('#pass').fill(password)
  await page.getByRole('button', { name: signup ? 'Create Account' : 'Sign In', exact: true }).click()
  await expect(page.locator('#main')).toBeVisible()
  await page.waitForFunction(() => ws?.readyState === WebSocket.OPEN)
}
async function screenshot(page, info, name) {
  const bytes = await page.screenshot({ path: info.outputPath(`${name}.jpg`), type: 'jpeg', quality: 60 })
  await info.attach(name, { body: bytes, contentType: 'image/jpeg' })
  // These test screens contain synthetic data only. This optional log copy lets
  // a reviewer inspect pixels even when their environment cannot download ZIPs.
  if (process.env.SCREENSHOT_LOGS === '1') console.log(`FREELAND_SCREENSHOT_${name.toUpperCase()}=${bytes.toString('base64')}`)
}

test('two accounts: realtime posts, likes, reshares, trades, private messages and logout', async ({ browser, page }, info) => {
  const failures = []
  page.on('pageerror', error => failures.push(error.message))
  const other = await browser.newContext({ baseURL: 'http://127.0.0.1:4318' })
  const bob = await other.newPage()
  bob.on('pageerror', error => failures.push(error.message))
  await signIn(page, 'ui_alice')
  await signIn(bob, 'ui_bob')
  await page.locator('#text').fill('Synthetic browser security check')
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await expect(bob.locator('.post-content')).toHaveText('Synthetic browser security check')
  await expect(page.locator('#balance')).toHaveText('💰 110')
  const original = bob.locator('.post').first()
  const id = (await original.getAttribute('id')).replace('post-', '')
  await bob.locator(`#like-${id}`).click()
  await expect(page.locator(`#like-count-${id}`)).toHaveText('1')
  await bob.locator(`#reshare-${id}`).click()
  await bob.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(bob.locator('.modal-overlay')).toHaveCount(0)
  await bob.locator(`#reshare-${id}`).click()
  await bob.locator('#reshare-text').fill('Synthetic reshare')
  await bob.getByRole('button', { name: 'Reshare', exact: true }).click()
  await expect(bob.getByText('Synthetic reshare', { exact: true })).toBeVisible()
  await bob.locator(`#reshare-${id}`).click()
  await bob.getByRole('button', { name: 'Reshare', exact: true }).click()
  await expect(bob.getByText('Synthetic reshare', { exact: true })).toHaveCount(0)
  await original.getByRole('button', { name: '📈 Buy', exact: true }).click()
  await expect(bob.locator('#balance')).toHaveText('💰 90')
  await bob.getByRole('button', { name: '💼 Portfolio', exact: true }).click()
  await bob.getByRole('button', { name: 'Sell for 💰10', exact: true }).click()
  await expect(bob.locator('#balance')).toHaveText('💰 100')
  for (const client of [page, bob]) {
    await client.getByRole('button', { name: '💬 DM', exact: true }).click()
    await client.getByRole('button', { name: 'Unlock DM (50💰)', exact: true }).click()
    await expect(client.locator('#dm-to')).toBeVisible()
  }
  await page.locator('#dm-to').fill('ui_bob')
  await page.locator('#dm-text').fill('Private synthetic browser message')
  await page.getByRole('button', { name: 'Send Message', exact: true }).click()
  await expect(bob.getByText('Private synthetic browser message', { exact: true })).toBeVisible()
  const anonymous = await browser.newContext()
  expect((await anonymous.request.get('http://127.0.0.1:4318/api/messages?uid=1')).status()).toBe(401)
  await anonymous.close()
  await page.getByRole('button', { name: '📰 Feed', exact: true }).click()
  await screenshot(page, info, 'desktop')
  await page.reload()
  await expect(page.locator('#main')).toBeVisible()
  await page.getByRole('button', { name: '📊 Stats', exact: true }).click()
  await expect(page.locator('#dashboard .stats-grid')).toBeVisible()
  await page.getByRole('button', { name: 'Exit', exact: true }).click()
  await expect(page.locator('#auth')).toBeVisible()
  await expect(page.locator('#dm-view')).toBeEmpty()
  expect((await page.request.get('/api/messages?uid=2')).status()).toBe(401)
  await page.reload()
  await expect(page.locator('#auth')).toBeVisible()
  await expect(page.locator('#main')).toBeHidden()
  await signIn(page, 'ui_alice', false)
  expect(failures).toEqual([])
  await other.close()
})

test('repeated login, multiple tabs, failed logout and session expiry stay recoverable', async ({ page, context }) => {
  const failures = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('/')
  await page.locator('#user').fill('ui_tabs')
  await page.locator('#pass').fill(password)
  await page.getByRole('button', { name: 'Create Account', exact: true }).dblclick()
  await expect(page.locator('#main')).toBeVisible()
  await page.waitForFunction(() => ws?.readyState === WebSocket.OPEN)
  const second = await context.newPage()
  await second.goto('/')
  await expect(second.locator('#main')).toBeVisible()
  await second.waitForFunction(() => ws?.readyState === WebSocket.OPEN)
  await second.close()
  await page.locator('#text').fill('Synthetic surviving tab')
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await expect(page.locator('#balance')).toHaveText('💰 110')
  await page.route('**/api/logout', route => route.abort())
  await page.getByRole('button', { name: 'Exit', exact: true }).click()
  await expect(page.locator('#notification')).toContainText('Could not sign out on the server')
  await expect(page.locator('#main')).toBeVisible()
  await page.unroute('**/api/logout')
  await page.route('**/api/stats', route => route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"Sign in required"}' }))
  await page.getByRole('button', { name: '📊 Stats', exact: true }).click()
  await expect(page.locator('#auth')).toBeVisible()
  await expect(page.locator('#feed')).toBeEmpty()
  await page.unroute('**/api/stats')
  // Explicitly finish the still-live synthetic server session after the mocked expiry.
  const response = await page.request.post('/api/logout', { headers: { Origin: 'http://127.0.0.1:4318' } })
  expect(response.ok()).toBeTruthy()
  expect(failures).toEqual([])
})

test('mobile login renders without horizontal overflow', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Sign In', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await screenshot(page, info, 'mobile')
})
